name: Build Search Index

on:
  push:
    branches:
      - main

jobs:
  algolia:
    runs-on: "ubuntu-latest"

  steps:
    - name: Get the content of algolia.json as config
      uses: actions/checkout@v2
      id: algolia_config
      run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"

    - name: Push indices to Algolia
      uses: signcl/docsearch-scraper-action@master
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        CONFIG: ${{ steps.algolia_config.outputs.config }}
