name: Build Search Index

on:
  push:
    branches:
      - main

jobs:
  algolia:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Get algolia as config
        id: algolia_config
        run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"

      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: {"index_name":"docs","start_urls":["https://euphonious-cassata-c433db.netlify.app"],"sitemap_urls":["https://euphonious-cassata-c433db.netlify.app/sitemap.xml"],"sitemap_alternate_links":true,"stop_urls":[],"selectors":{"lvl1":"header h1","lvl2":"article h2","lvl3":"article h3","lvl4":"article h4","lvl5":"article h5, article td:first-child","lvl6":"article h6","text":"article p, article li, article td:last-child"},"strip_chars":" .,;:#","custom_settings":{"separatorsToIndex":"_","attributesForFaceting":["language","version","type","docusaurus_tag"],"attributesToRetrieve":["hierarchy","content","anchor","url","url_without_anchor","type"]}}
